language: go

addons:
  apt:
    packages:
      - sshpass
  
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_extended_0.56.3_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.56.3_Linux-64bit.deb

script:
  - hugo

after_success:
  - export SSHPASS=$DEPLOYMENT_PASSWORD
  - sshpass -e scp -o stricthostkeychecking=no -r public/* $DEPLOYMENT_USER@$DEPLOYMENT_HOST:~$DEPLOYMENT_PATH
