language: go

branches:
  only:
    - master

before_install:
- openssl aes-256-cbc -K $encrypted_a5ccc7f84a63_key -iv $encrypted_a5ccc7f84a63_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key -o "StrictHostKeyChecking=no" $DEPLOYMENT_USER@$DEPLOYMENT_HOST pwd

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb

script:
  - hugo version
  - hugo

after_success:
  - scp -o stricthostkeychecking=no -r public/* $DEPLOYMENT_USER@$DEPLOYMENT_HOST:~$DEPLOYMENT_PATH

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.76.5
